// _TaskDialog_EOArchive_English.java
// Generated by EnterpriseObjects palette at Sonntag, M\u00e4rz 02, 2003 12:56:48 Europe/Berlin

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _TaskDialog_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField16, _nsTextField17, _nsTextField18, _nsTextField19, _nsTextField2, _nsTextField20, _nsTextField21, _nsTextField22, _nsTextField23, _nsTextField24, _nsTextField25, _nsTextField26, _nsTextField27, _nsTextField28, _nsTextField29, _nsTextField3, _nsTextField30, _nsTextField31, _nsTextField32, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsSlider0, _nsSlider1, _nsSlider2, _nsSlider3, _nsView0, _nsView1, _nsView2;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2;
    javax.swing.JCheckBox _nsButton10, _nsButton11, _nsButton12, _nsButton13, _nsButton14, _nsButton15, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8, _nsButton9;
    javax.swing.JComboBox _popup0, _popup1, _popup2, _popup3, _popup4;
    javax.swing.JPanel _nsView3;
    javax.swing.JTabbedPane _nsTabView0;

    public _TaskDialog_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField32 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField112");
        _nsTextField31 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11231");
        _nsTextField30 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1112");
        _nsTextField29 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11211");
        _nsTextField28 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1121");
        _nsTextField27 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _popup4 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton311");
        _nsTextField26 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField5211");
        _popup3 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton211");
        _nsTextField25 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsTextField24 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField4112");
        _popup2 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton411");
        _popup1 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton511");
        _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton11");
        _nsTextField23 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1122");
        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsTextField22 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111");
        _nsTextField21 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        _nsTextField20 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111511");
        _nsTextField19 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111611");
        _nsTextField18 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111311");
        _nsTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111211");
        _nsTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111711");
        _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111411");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "weCheckbox")) != null)) {
            _nsButton15 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton15");
        } else {
            _nsButton15 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton4211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "wdayTextField")) != null)) {
            _nsTextField14 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField14");
        } else {
            _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField51111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "thCheckbox")) != null)) {
            _nsButton14 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton14");
        } else {
            _nsButton14 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton4311");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "suCheckbox")) != null)) {
            _nsButton13 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton13");
        } else {
            _nsButton13 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton4611");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "submitButton")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Apply"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "simpleMonthTextField")) != null)) {
            _nsTextField13 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField13");
        } else {
            _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField521");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "simpleMinuteTextField")) != null)) {
            _nsTextField12 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField12");
        } else {
            _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "simpleMdayTextField")) != null)) {
            _nsTextField11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField11");
        } else {
            _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField411");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "simpleHourTextField")) != null)) {
            _nsTextField10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField10");
        } else {
            _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField311");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "monthTextField")) != null)) {
            _nsTextField9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField9");
        } else {
            _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField5111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "mdayTextField")) != null)) {
            _nsTextField8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField8");
        } else {
            _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField4111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "hourTextField")) != null)) {
            _nsTextField7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField7");
        } else {
            _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField3111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "minuteTextField")) != null)) {
            _nsTextField6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField6");
        } else {
            _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField7111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "saCheckbox")) != null)) {
            _nsButton12 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton12");
        } else {
            _nsButton12 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton4411");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "openCheckbox")) != null)) {
            _nsButton11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton11");
        } else {
            _nsButton11 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Prepend \"/usr/bin/open\""), "NSButton4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "monthSlider")) != null)) {
            _nsSlider3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider3");
        } else {
            _nsSlider3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider1211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "moCheckbox")) != null)) {
            _nsButton10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton10");
        } else {
            _nsButton10 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton411");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "minuteSlider")) != null)) {
            _nsSlider2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider2");
        } else {
            _nsSlider2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider131");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "mdaySlider")) != null)) {
            _nsSlider1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider1");
        } else {
            _nsSlider1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider1311");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "hourSlider")) != null)) {
            _nsSlider0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider0");
        } else {
            _nsSlider0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider1111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "frCheckbox")) != null)) {
            _nsButton9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton9");
        } else {
            _nsButton9 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton4511");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "commandTextField")) != null)) {
            _nsTextField5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField5");
        } else {
            _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "browseButton")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Browse..."), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "anyWdayCheckbox")) != null)) {
            _nsButton8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton8");
        } else {
            _nsButton8 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton4112");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "anyMonthCheckbox")) != null)) {
            _nsButton7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton7");
        } else {
            _nsButton7 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton41124");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "anyMinuteCheckbox")) != null)) {
            _nsButton6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton6");
        } else {
            _nsButton6 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton41121");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "anyMdayCheckbox")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton41123");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "anyHourCheckbox")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton41122");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tuCheckbox")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "NSButton411111");
        }

        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "NSTabView");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1411");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1211");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1311");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1121");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField151");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel1");
        }

        _nsView3 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _popup4.setModel(new javax.swing.DefaultComboBoxModel());
        _popup4.addItem("Every");
        _popup4.addItem("Item2");
        _popup4.addItem("Item3");
        _popup3.setModel(new javax.swing.DefaultComboBoxModel());
        _popup3.addItem("Every");
        _popup3.addItem("Any");
        _popup3.addItem("Item3");
        _popup2.setModel(new javax.swing.DefaultComboBoxModel());
        _popup2.addItem("Every");
        _popup2.addItem("Item2");
        _popup2.addItem("Item3");
        _popup1.setModel(new javax.swing.DefaultComboBoxModel());
        _popup1.addItem("Every");
        _popup1.addItem("Any");
        _popup1.addItem("Item3");
        _popup0.setModel(new javax.swing.DefaultComboBoxModel());
        _popup0.addItem("Every");
        _popup0.addItem("Any");
        _popup0.addItem("Between");
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "cancelButtonClicked", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_eoFrame0, _owner(), "delegate");
        }

        _nsButton15.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "wdayCheckboxClicked", _nsButton15), ""));

        if (_replacedObjects.objectForKey("_nsButton15") == null) {
            _connect(_owner(), _nsButton15, "weCheckbox");
        }

        if (_replacedObjects.objectForKey("_nsTextField14") == null) {
            _connect(_nsTextField14, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField14") == null) {
            _connect(_owner(), _nsTextField14, "wdayTextField");
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "tuCheckbox");
        }

        _nsButton14.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "wdayCheckboxClicked", _nsButton14), ""));

        if (_replacedObjects.objectForKey("_nsButton14") == null) {
            _connect(_owner(), _nsButton14, "thCheckbox");
        }

        _nsButton13.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "wdayCheckboxClicked", _nsButton13), ""));

        if (_replacedObjects.objectForKey("_nsButton13") == null) {
            _connect(_owner(), _nsButton13, "suCheckbox");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "acceptButtonClicked", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "submitButton");
        }

        if (_replacedObjects.objectForKey("_nsTextField13") == null) {
            _connect(_nsTextField13, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField13") == null) {
            _connect(_owner(), _nsTextField13, "simpleMonthTextField");
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _connect(_nsTextField12, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _connect(_owner(), _nsTextField12, "simpleMinuteTextField");
        }

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _connect(_nsTextField11, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _connect(_owner(), _nsTextField11, "simpleMdayTextField");
        }

        if (_replacedObjects.objectForKey("_nsTextField10") == null) {
            _connect(_nsTextField10, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField10") == null) {
            _connect(_owner(), _nsTextField10, "simpleHourTextField");
        }

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _connect(_nsTextField9, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _connect(_owner(), _nsTextField9, "monthTextField");
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _connect(_nsTextField8, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _connect(_owner(), _nsTextField8, "mdayTextField");
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _connect(_nsTextField7, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _connect(_owner(), _nsTextField7, "hourTextField");
        }

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _connect(_nsTextField6, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _connect(_owner(), _nsTextField6, "minuteTextField");
        }

        _nsButton12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "wdayCheckboxClicked", _nsButton12), ""));

        if (_replacedObjects.objectForKey("_nsButton12") == null) {
            _connect(_owner(), _nsButton12, "saCheckbox");
        }

        _nsButton11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "openCheckboxClicked", _nsButton11), ""));

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _connect(_owner(), _nsButton11, "openCheckbox");
        }

        _nsSlider3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "sliderMoved", _nsSlider3), ""));

        if (_replacedObjects.objectForKey("_nsSlider3") == null) {
            _connect(_owner(), _nsSlider3, "monthSlider");
        }

        _nsButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "wdayCheckboxClicked", _nsButton10), ""));

        if (_replacedObjects.objectForKey("_nsButton10") == null) {
            _connect(_owner(), _nsButton10, "moCheckbox");
        }

        _nsSlider2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "sliderMoved", _nsSlider2), ""));

        if (_replacedObjects.objectForKey("_nsSlider2") == null) {
            _connect(_owner(), _nsSlider2, "minuteSlider");
        }

        _nsSlider1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "sliderMoved", _nsSlider1), ""));

        if (_replacedObjects.objectForKey("_nsSlider1") == null) {
            _connect(_owner(), _nsSlider1, "mdaySlider");
        }

        _nsSlider0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "sliderMoved", _nsSlider0), ""));

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _connect(_owner(), _nsSlider0, "hourSlider");
        }

        _nsButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "wdayCheckboxClicked", _nsButton9), ""));

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _connect(_owner(), _nsButton9, "frCheckbox");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_nsTextField5, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_owner(), _nsTextField5, "commandTextField");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "browseButtonClicked", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "browseButton");
        }

        _nsButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "anyWdayCheckboxClicked", _nsButton8), ""));

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _connect(_owner(), _nsButton8, "anyWdayCheckbox");
        }

        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "anyMonthCheckboxClicked", _nsButton7), ""));

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _connect(_owner(), _nsButton7, "anyMonthCheckbox");
        }

        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "anyMinuteCheckboxClicked", _nsButton6), ""));

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _connect(_owner(), _nsButton6, "anyMinuteCheckbox");
        }

        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "anyMdayCheckboxClicked", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "anyMdayCheckbox");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "anyHourCheckboxClicked", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "anyHourCheckbox");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "wdayCheckboxClicked", _nsButton3), ""));
    }

    protected void _init() {
        super._init();
        if (!(_nsBox5.getLayout() instanceof EOViewLayout)) { _nsBox5.setLayout(new EOViewLayout()); }
        _nsTextField5.setSize(352, 45);
        _nsTextField5.setLocation(15, 11);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField5);
        _nsButton11.setSize(180, 17);
        _nsButton11.setLocation(12, 69);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsButton11, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsButton11);
        _nsButton0.setSize(91, 26);
        _nsButton0.setLocation(279, 65);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox5.add(_nsButton0);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(380, 101);
        _nsBox5.setLocation(2, 18);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Command", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsTextField6.setSize(219, 19);
        _nsTextField6.setLocation(18, 20);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsTextField6);
        _nsTextField7.setSize(219, 19);
        _nsTextField7.setLocation(18, 47);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsTextField7);
        _nsTextField9.setSize(219, 19);
        _nsTextField9.setLocation(18, 101);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsTextField9);
        _nsTextField8.setSize(219, 19);
        _nsTextField8.setLocation(18, 74);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsTextField8);
        _nsTextField14.setSize(219, 19);
        _nsTextField14.setLocation(18, 128);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsTextField14);
        _setFontForComponent(_nsTextField32, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField32.setEditable(false);
        _nsTextField32.setOpaque(false);
        _nsTextField32.setText("This is a non-functional samle tab.");
        _nsTextField32.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField32.setSelectable(false);
        _nsTextField32.setEnabled(true);
        _nsTextField32.setBorder(null);
        _setFontForComponent(_nsTextField31, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField31.setEditable(false);
        _nsTextField31.setOpaque(false);
        _nsTextField31.setText("hour");
        _nsTextField31.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField31.setSelectable(false);
        _nsTextField31.setEnabled(true);
        _nsTextField31.setBorder(null);
        _setFontForComponent(_nsTextField30, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField30.setEditable(true);
        _nsTextField30.setOpaque(true);
        _nsTextField30.setText("30");
        _nsTextField30.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField30.setSelectable(true);
        _nsTextField30.setEnabled(false);
        _setFontForComponent(_nsTextField29, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField29.setEditable(false);
        _nsTextField29.setOpaque(false);
        _nsTextField29.setText("weekday");
        _nsTextField29.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField29.setSelectable(false);
        _nsTextField29.setEnabled(true);
        _nsTextField29.setBorder(null);
        _setFontForComponent(_nsTextField28, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField28.setEditable(false);
        _nsTextField28.setOpaque(false);
        _nsTextField28.setText("nd/th");
        _nsTextField28.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField28.setSelectable(false);
        _nsTextField28.setEnabled(true);
        _nsTextField28.setBorder(null);
        _setFontForComponent(_nsTextField27, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField27.setEditable(false);
        _nsTextField27.setOpaque(false);
        _nsTextField27.setText("nd/th");
        _nsTextField27.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField27.setSelectable(false);
        _nsTextField27.setEnabled(true);
        _nsTextField27.setBorder(null);
        _setFontForComponent(_popup4, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsTextField26, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField26.setEditable(true);
        _nsTextField26.setOpaque(true);
        _nsTextField26.setText("4");
        _nsTextField26.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField26.setSelectable(true);
        _nsTextField26.setEnabled(false);
        _setFontForComponent(_popup3, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsTextField25, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField25.setEditable(true);
        _nsTextField25.setOpaque(true);
        _nsTextField25.setText("0");
        _nsTextField25.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField25.setSelectable(true);
        _nsTextField25.setEnabled(false);
        _setFontForComponent(_nsTextField24, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField24.setEditable(true);
        _nsTextField24.setOpaque(true);
        _nsTextField24.setText("2");
        _nsTextField24.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField24.setSelectable(true);
        _nsTextField24.setEnabled(false);
        _setFontForComponent(_popup2, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_popup1, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_popup0, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsTextField23, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField23.setEditable(false);
        _nsTextField23.setOpaque(false);
        _nsTextField23.setText("and");
        _nsTextField23.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField23.setSelectable(false);
        _nsTextField23.setEnabled(true);
        _nsTextField23.setBorder(null);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsTextField23.setSize(129, 14);
        _nsTextField23.setLocation(180, 23);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField23, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField23);
        _popup0.setSize(121, 22);
        _popup0.setLocation(22, 20);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView1.add(_popup0);
        _popup1.setSize(121, 22);
        _popup1.setLocation(22, 128);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_popup1, EOViewLayout.MinYMargin);
        _nsView1.add(_popup1);
        _popup2.setSize(121, 22);
        _popup2.setLocation(22, 101);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_popup2, EOViewLayout.MinYMargin);
        _nsView1.add(_popup2);
        _nsTextField24.setSize(24, 19);
        _nsTextField24.setLocation(151, 74);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField24, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField24);
        _nsTextField25.setSize(24, 19);
        _nsTextField25.setLocation(151, 20);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField25, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField25);
        _popup3.setSize(121, 22);
        _popup3.setLocation(22, 47);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_popup3, EOViewLayout.MinYMargin);
        _nsView1.add(_popup3);
        _nsTextField26.setSize(24, 19);
        _nsTextField26.setLocation(151, 101);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField26, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField26);
        _popup4.setSize(121, 22);
        _popup4.setLocation(22, 74);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_popup4, EOViewLayout.MinYMargin);
        _nsView1.add(_popup4);
        _nsTextField27.setSize(129, 14);
        _nsTextField27.setLocation(180, 76);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField27, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField27);
        _nsTextField28.setSize(129, 14);
        _nsTextField28.setLocation(180, 104);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField28, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField28);
        _nsTextField29.setSize(129, 14);
        _nsTextField29.setLocation(148, 131);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField29, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField29);
        _nsTextField30.setSize(24, 19);
        _nsTextField30.setLocation(210, 20);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField30, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField30);
        _nsTextField31.setSize(129, 14);
        _nsTextField31.setLocation(148, 49);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField31, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField31);
        _nsTextField32.setSize(253, 14);
        _nsTextField32.setLocation(18, 0);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField32, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField32);
        _setFontForComponent(_nsTextField22, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField22.setEditable(false);
        _nsTextField22.setOpaque(false);
        _nsTextField22.setText("Mo");
        _nsTextField22.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField22.setSelectable(false);
        _nsTextField22.setEnabled(true);
        _nsTextField22.setBorder(null);
        _setFontForComponent(_nsTextField21, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField21.setEditable(false);
        _nsTextField21.setOpaque(false);
        _nsTextField21.setText("Tu");
        _nsTextField21.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField21.setSelectable(false);
        _nsTextField21.setEnabled(true);
        _nsTextField21.setBorder(null);
        _setFontForComponent(_nsTextField20, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField20.setEditable(false);
        _nsTextField20.setOpaque(false);
        _nsTextField20.setText("Sa");
        _nsTextField20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField20.setSelectable(false);
        _nsTextField20.setEnabled(true);
        _nsTextField20.setBorder(null);
        _setFontForComponent(_nsTextField19, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField19.setEditable(false);
        _nsTextField19.setOpaque(false);
        _nsTextField19.setText("Su");
        _nsTextField19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField19.setSelectable(false);
        _nsTextField19.setEnabled(true);
        _nsTextField19.setBorder(null);
        _setFontForComponent(_nsTextField18, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField18.setEditable(false);
        _nsTextField18.setOpaque(false);
        _nsTextField18.setText("We");
        _nsTextField18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField18.setSelectable(false);
        _nsTextField18.setEnabled(true);
        _nsTextField18.setBorder(null);
        _setFontForComponent(_nsTextField17, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField17.setEditable(false);
        _nsTextField17.setOpaque(false);
        _nsTextField17.setText("Th");
        _nsTextField17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField17.setSelectable(false);
        _nsTextField17.setEnabled(true);
        _nsTextField17.setBorder(null);
        _setFontForComponent(_nsTextField16, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField16.setEditable(false);
        _nsTextField16.setOpaque(false);
        _nsTextField16.setText("Any");
        _nsTextField16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField16.setSelectable(false);
        _nsTextField16.setEnabled(true);
        _nsTextField16.setBorder(null);
        _setFontForComponent(_nsTextField15, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField15.setEditable(false);
        _nsTextField15.setOpaque(false);
        _nsTextField15.setText("Fr");
        _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField15.setSelectable(false);
        _nsTextField15.setEnabled(true);
        _nsTextField15.setBorder(null);
        _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsButton15") == null) {
            _setFontForComponent(_nsButton15, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField14") == null) {
            _setFontForComponent(_nsTextField14, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField14.setEditable(true);
            _nsTextField14.setOpaque(true);
            _nsTextField14.setText("*");
            _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField14.setSelectable(true);
            _nsTextField14.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton14") == null) {
            _setFontForComponent(_nsButton14, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton13") == null) {
            _setFontForComponent(_nsButton13, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsTextField13") == null) {
            _setFontForComponent(_nsTextField13, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField13.setEditable(true);
            _nsTextField13.setOpaque(true);
            _nsTextField13.setText("*");
            _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField13.setSelectable(true);
            _nsTextField13.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _setFontForComponent(_nsTextField12, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField12.setEditable(true);
            _nsTextField12.setOpaque(true);
            _nsTextField12.setText("0");
            _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField12.setSelectable(true);
            _nsTextField12.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _setFontForComponent(_nsTextField11, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField11.setEditable(true);
            _nsTextField11.setOpaque(true);
            _nsTextField11.setText("*");
            _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField11.setSelectable(true);
            _nsTextField11.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField10") == null) {
            _setFontForComponent(_nsTextField10, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField10.setEditable(true);
            _nsTextField10.setOpaque(true);
            _nsTextField10.setText("0");
            _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField10.setSelectable(true);
            _nsTextField10.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _setFontForComponent(_nsTextField9, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField9.setEditable(true);
            _nsTextField9.setOpaque(true);
            _nsTextField9.setText("*");
            _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField9.setSelectable(true);
            _nsTextField9.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _setFontForComponent(_nsTextField8, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField8.setEditable(true);
            _nsTextField8.setOpaque(true);
            _nsTextField8.setText("*");
            _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField8.setSelectable(true);
            _nsTextField8.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _setFontForComponent(_nsTextField7, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField7.setEditable(true);
            _nsTextField7.setOpaque(true);
            _nsTextField7.setText("0");
            _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField7.setSelectable(true);
            _nsTextField7.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _setFontForComponent(_nsTextField6, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField6.setEditable(true);
            _nsTextField6.setOpaque(true);
            _nsTextField6.setText("0");
            _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField6.setSelectable(true);
            _nsTextField6.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton12") == null) {
            _setFontForComponent(_nsButton12, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _setFontForComponent(_nsButton11, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsSlider3") == null) {
            _setFontForComponent(_nsSlider3, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton10") == null) {
            _setFontForComponent(_nsButton10, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsSlider2") == null) {
            _setFontForComponent(_nsSlider2, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsSlider1") == null) {
            _setFontForComponent(_nsSlider1, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _setFontForComponent(_nsSlider0, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _setFontForComponent(_nsButton9, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _setFontForComponent(_nsTextField5, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField5.setEditable(true);
            _nsTextField5.setOpaque(true);
            _nsTextField5.setText("");
            _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField5.setSelectable(true);
            _nsTextField5.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _setFontForComponent(_nsButton8, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _setFontForComponent(_nsButton7, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _setFontForComponent(_nsButton6, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 11, Font.PLAIN);
        }

        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(26, 148);
        _nsBox3.setLocation(3, 3);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox2.setSize(32, 154);
        _nsBox2.setLocation(9, 17);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox2);
        _nsButton3.setSize(22, 17);
        _nsButton3.setLocation(78, 130);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton3);
        _nsButton13.setSize(22, 17);
        _nsButton13.setLocation(213, 130);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton13, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton13);
        _nsTextField15.setSize(19, 14);
        _nsTextField15.setLocation(161, 153);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField15);
        _nsTextField16.setSize(27, 14);
        _nsTextField16.setLocation(15, 153);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField16, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField16);
        _nsButton9.setSize(22, 17);
        _nsButton9.setLocation(159, 130);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton9, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton9);
        _nsButton12.setSize(22, 17);
        _nsButton12.setLocation(186, 130);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton12, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton12);
        _nsButton14.setSize(22, 17);
        _nsButton14.setLocation(132, 130);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton14, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton14);
        _nsTextField13.setSize(24, 19);
        _nsTextField13.setLocation(48, 101);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField13);
        _nsTextField17.setSize(19, 14);
        _nsTextField17.setLocation(134, 153);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField17, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField17);
        _nsTextField12.setSize(24, 19);
        _nsTextField12.setLocation(48, 20);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField12);
        _nsSlider2.setSize(154, 15);
        _nsSlider2.setLocation(79, 24);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsSlider2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsSlider2);
        _nsTextField18.setSize(19, 14);
        _nsTextField18.setLocation(107, 153);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField18, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField18);
        _nsButton8.setSize(22, 17);
        _nsButton8.setLocation(16, 130);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton8);
        _nsSlider1.setSize(154, 15);
        _nsSlider1.setLocation(79, 78);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsSlider1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsSlider1);
        _nsSlider0.setSize(154, 15);
        _nsSlider0.setLocation(79, 51);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsSlider0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsSlider0);
        _nsTextField19.setSize(19, 14);
        _nsTextField19.setLocation(215, 153);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField19, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField19);
        _nsTextField10.setSize(24, 19);
        _nsTextField10.setLocation(48, 47);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField10);
        _nsButton15.setSize(22, 17);
        _nsButton15.setLocation(105, 130);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton15, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton15);
        _nsButton10.setSize(22, 17);
        _nsButton10.setLocation(51, 130);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton10, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton10);
        _nsSlider3.setSize(154, 15);
        _nsSlider3.setLocation(79, 105);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsSlider3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsSlider3);
        _nsTextField20.setSize(19, 14);
        _nsTextField20.setLocation(188, 153);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField20, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField20);
        _nsTextField21.setSize(19, 14);
        _nsTextField21.setLocation(80, 153);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField21, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField21);
        _nsTextField11.setSize(24, 19);
        _nsTextField11.setLocation(48, 74);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField11);
        _nsTextField22.setSize(19, 14);
        _nsTextField22.setLocation(53, 153);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField22, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField22);
        _nsButton6.setSize(22, 17);
        _nsButton6.setLocation(16, 22);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton6);
        _nsButton4.setSize(22, 17);
        _nsButton4.setLocation(16, 49);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton4);
        _nsButton5.setSize(22, 17);
        _nsButton5.setLocation(16, 76);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton5);
        _nsButton7.setSize(22, 17);
        _nsButton7.setLocation(16, 103);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton7);
        _nsTabView0.addTab("Simple", _nsView0);
        _nsTabView0.addTab("Intervals", _nsView1);
        _nsTabView0.addTab("Expert", _nsView2);
        _setFontForComponent(_nsTextField4, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Month");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("Day of month");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Day of week");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Hour");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Minute\n\n");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(91, 14);
        _nsTextField0.setLocation(14, 62);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField0);
        _nsTextField1.setSize(91, 14);
        _nsTextField1.setLocation(14, 89);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField1);
        _nsTextField2.setSize(91, 14);
        _nsTextField2.setLocation(14, 170);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField2);
        _nsTextField3.setSize(91, 14);
        _nsTextField3.setLocation(14, 116);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField3);
        _nsTextField4.setSize(91, 14);
        _nsTextField4.setLocation(14, 143);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField4);
        _nsTabView0.setSize(263, 227);
        _nsTabView0.setLocation(104, 8);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTabView0);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(380, 243);
        _nsBox1.setLocation(2, 18);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Schedule", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(384, 263);
        _nsBox0.setLocation(13, 1);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView3.add(_nsBox0);
        _nsBox4.setSize(384, 121);
        _nsBox4.setLocation(13, 271);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.MinYMargin);
        _nsView3.add(_nsBox4);
        _nsButton1.setSize(77, 26);
        _nsButton1.setLocation(324, 410);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton1);
        _nsButton2.setSize(77, 26);
        _nsButton2.setLocation(240, 410);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton2);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView3.setSize(410, 446);
            _eoFrame0.setTitle("");
            _eoFrame0.setLocation(146, 302);
            _eoFrame0.setSize(410, 446);
        }
    }
}
